// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mrxacrnjclghcmgdckvr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1yeGFjcm5qY2xnaGNtZ2Rja3ZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5MTU0MTEsImV4cCI6MjA3MzQ5MTQxMX0.FasTwJVfMTXLdrQHu7AiTVYIuBI4XjQ4kv8EOL3FMAQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});